### ISSUE TITLE
Breaking naming pattern change without migration path

### ISSUE THREAD

**Issue by frits-v** [lacework/terraform-gcp-audit-log#56]
Pre v1.0 module creates buckets with a slightly different naming pattern. The naming change forces a terraform destroy/create and there's no clear upgrade path or workaround, other than doing state surgery and/or bucket migrations. 

https://github.com/lacework/terraform-gcp-audit-log/commit/910d03fb5d41dae876231881db2d77e0a994f569 

https://github.com/lacework/terraform-gcp-audit-log/blob/46c54f7ee1953104a4a2e119801e527493192956/main.tf#L108

**Comment by afiune** [comment]
Closing in favor of https://github.com/lacework/terraform-gcp-audit-log/pull/57
