### ISSUE TITLE
bug: Provider Constraint Conflict between this module and service account module

### ISSUE THREAD

**Issue by Simonx123** [lacework/terraform-gcp-audit-log#67]
**Describe the bug**
When running terraform init, got the following error 

```
Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider hashicorp/google: no available releases match the given constraints >= 3.0.0, ~> 3.0, >= 4.4.0,
│ < 5.0.0
```

The provider in gcp-service-account module https://github.com/lacework/terraform-gcp-service-account/blob/e39056f90a624c983af3d0a0b44dc4922e31fd06/versions.tf#L5 is conflicting with 
https://github.com/lacework/terraform-gcp-audit-log/blob/5b824a104ea8c78cc915e301fb7f95108ab00e4a/versions.tf#L5

**Steps to reproduce**
Run terraform init

**Expected behavior**
terraform init run successfully

**Screenshots**

**Please complete the following information):**
 - Terraform Version: [e.g. v1.1.3 ]

Run `terraform version` to find your Terraform version.
You can find the module version by running `terraform providers` or in your terraform configuration. If developing locally you can check the `VERSION` file in the project root directory.

**Additional context**

**Comment by afiune** [comment]
Hi @Simonx123 - Thank you for your feedback!

The version constraint shouldn't be a problem if you are using the google provider version `4.4.0` or above,
I just tested a brand new Terraform plan with vanilla code from the [Terraform Registry](https://registry.terraform.io/modules/lacework/audit-log/gcp/3.3.3):
### `main.tf`
```tf
module "audit-log" {
  source  = "lacework/audit-log/gcp"
  version = "3.3.3"
  # insert the 1 required variable here
}
```
And ran `terraform init` without issues.
```
# terraform init
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Reusing previous version of hashicorp/random from the dependency lock file
- Reusing previous version of hashicorp/google from the dependency lock file
- Reusing previous version of hashicorp/time from the dependency lock file
- Reusing previous version of lacework/lacework from the dependency lock file
- Using previously-installed hashicorp/random v3.3.2
- Using previously-installed hashicorp/google v4.28.0
- Using previously-installed hashicorp/time v0.7.2
- Using previously-installed lacework/lacework v0.21.0

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```
Checking versions:
```
# terraform version
Terraform v1.1.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v4.28.0
+ provider registry.terraform.io/hashicorp/random v3.3.2
+ provider registry.terraform.io/hashicorp/time v0.7.2
+ provider registry.terraform.io/lacework/lacework v0.21.0

Your version of Terraform is out of date! The latest version
is 1.2.4. You can update by downloading from https://www.terraform.io/downloads.html
```

Having said that, I think you might be using an older version of the google provider, could you try upgrading
it and see if that fixes your problem?

Regardless of the outcome of that 👆🏽command, we will go ahead an sync the versions defined
in the service-account module you pointed out, but we won't support older versions of the google 
provider so you would have to upgrade to `4.4.0` or above.

**Comment by Simonx123** [comment]
I think the issue was because I was deploying it along with 

```
module "gcp_organization_config" {
  source  = "lacework/config/gcp"
 ```

On `version 1.2.0.`  That has contraint peg to =~3.0

I change that to `version 2.0.0`.

terraform init works now. 

Thanks
