### ISSUE TITLE
feat: Remove the `< 4.41.0` hashicorp/google provider version constraint

### ISSUE THREAD

**Issue by lra** [lacework/terraform-gcp-audit-log#75]
# Feature Request

**Describe the Feature Request**
Remove the `< 4.41.0` hashicorp/google provider version constraint

**Is your feature request related to a problem? Please describe**
It's the only module that prevent us to upgrade our google provider, and it leads to other issues as some problems are only fixed in 4.41+.

**Describe Preferred Solution**
Replace `>= 4.4.0, < 4.41.0` with `>= 4.4.0, < 5.0.0` like in other lacework modules.

**Comment by dmurray-lacework** [comment]
Hi @lra  this has been fixed in this PR https://github.com/lacework/terraform-gcp-audit-log/commit/92261b8912ca1f9ff54b7b9756194625c59182cd

**Comment by lra** [comment]
Thanks, waiting for the release.

**Comment by dmurray-lacework** [comment]
Resolved in https://github.com/lacework/terraform-gcp-audit-log/releases/tag/v3.4.2
